name: CD

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Set Project Version
        uses: vers-one/dotnet-project-version-updater@v1.0
        with:
          file: src/Acme.Dapr.Extensions.UnitTesting/Acme.Dapr.Extensions.UnitTesting.csproj
          version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}.${{ env.NUMBER_OF_COMMITS_SINCE_TAG }}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src

      - name: Test --configuration Release
        run: dotnet test --no-build --verbosity normal --configuration Release
        working-directory: ./src

      - name: Pack
        run: dotnet pack --configuration Release
        working-directory: ./src

      - name: Push
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --no-symbols --source https://api.nuget.org/v3/index.json